#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo  -e "Content-type: text/html \n\n"
echo "<html>"
echo "<head>"
echo "<title>NFS设置</title>"
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />"
echo "</head>"
echo "<body>"
echo "<center>"
echo "<h3>NFS服务器设置</h3>"
echo "</center>"
echo "<hr>"
    echo "<center>"
    echo "<br><br>"
    echo "<form action=\"/cgi-bin/donfssetting.cgi\" method=POST>"
    echo "<table>"
        echo "<tr>"
            echo "<td>NFS服务器地址</td>"
            echo "<td><input type=\"text\" name=\"nfsip\" ></td>"
            echo "<td><input type=\"submit\" value="提交" ></td>"
        echo "</tr>"
    echo "</table>"
    echo "</form>"
    echo "</center>"
echo "</body>"
echo "</html>"
