#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo  -e "Content-type: text/html \n\n"
echo "<html>"
echo "<head>"
echo "<title>重启系统</title>"
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />"
echo "</head>"
echo "<body>"
echo "<center>"
echo "<h3>重启系统</h3>"
echo "</center>"
echo "<hr>"
    echo "<center>"
    echo "<br><br>"
    echo "<form action=\"/cgi-bin/doreboot.cgi\" method=POST>"
    echo "<table>"
        echo "<tr>"
            echo "<td><input type=\"hidden\" name=\"time\" value=\"1\"  ></td>"
            echo "<td><input type=\"submit\" value="立即重启" ></td>"
        echo "</tr>"
    echo "</table>"
    echo "</form>"
    echo "</center>"
echo "</body>"
echo "</html>"
