#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo  -e "Content-type: text/html \n\n"
echo "<html>"
echo "<head>"
echo "<title>应用升级</title>"
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />"
echo "</head>"
echo "<body>"
echo "<center>"
echo "<h3>应用升级</h3>"
echo "</center>"
echo "<hr>"
    echo "<center>"
    echo "<br><br>"
    echo "<form name=\"file\" action=\"/cgi-bin/doupapp.cgi\" enctype=multipart/form-data  method=POST>"
        echo "<table>"
            echo "<tr>"
                echo "<td>请选择文件:</td>"
                echo "<td><input type=\"file\" name=\"apacket\" ></td>"
                echo "<td><input type=\"submit\" value="上载"></td>"
            echo "</tr>"

        echo "</table>"
    echo "</form>"
                echo "<br><br>"
                echo "请遵循升级包标准格式：APPNAME.tar,升级包小于10M"
                echo "本升级程序默认行为是把升级包解压到/opt目录下"
    echo "</center>"
echo "</body>"
echo "</html>"
